tag files untar'ed by tar that was causing problems and add zopen_check_results function

diff --git a/buildenv b/buildenv
--- a/buildenv
+++ b/buildenv
@@ -6,10 +6,10 @@
 export ZOPEN_TYPE="TARBALL"
 
 export ZOPEN_TARBALL_URL="https://ftp.gnu.org/gnu/automake/automake-1.16.tar.gz"
-export ZOPEN_TARBALL_DEPS="curl gzip make m4 perl autoconf"
+export ZOPEN_TARBALL_DEPS="curl gzip make m4 perl autoconf tar"
 
 export ZOPEN_GIT_URL="https://github.com/autotools-mirror/automake.git"
-export ZOPEN_GIT_DEPS="git make m4 perl autoconf automake help2man makeinfo xz"
+export ZOPEN_GIT_DEPS="git make m4 perl autoconf automake help2man makeinfo xz tar"
 
 export ZOPEN_EXTRA_CFLAGS=""
 export ZOPEN_EXTRA_LDFLAGS=""
@@ -20,6 +20,17 @@ fi
 
 zopen_check_results()
 {
-  return 3 # non-functional
-}
+#!/bin/sh
+# automake should have less than 33 failures
+# Determine number of failures by looking at first word on lines and counting ERROR and FAIL
+#
+chk="$2_check.log"
 
+set -x
+failures=$(egrep '^ERROR|^FAIL' *16/*check.log | wc -l)
+if [ ${failures} -gt 33 ]; then
+  exit 2
+else
+  exit 1
+fi
+}
